const constant = {
  SUCCESS_STATUS_CODE: 200,
  CREATE_STATUS_CODE: 201,
  BAD_REQUEST_STATUS_CODE: 400,
  UNAUTHORIZED_STATUS_CODE: 401,
  FORBIDDEN_STATUS_CODE: 403,
  VALIDATION_TYPE_ERROR: "validationError",
  NOT_FOUND_STATUS_CODE: 404,
  SOMETHING_WENT_WRONG_STATUS_CODE: 500,
  PERMISSION_ERROR_STATUS_CODE: 403,
  ALREADY_EXIST_STATUS_CODE: 409,
  SOMETHING_WENT_WRONG: "Something went wrong, Please try again later.",
  SOMETHING_WENT_WRONG_TYPE: "internal_issue",
  WRONG_CREDENTIALS_TYPE: "invalid_grant",
  NOT_FOUND_ERROR: "Not found",
  RECORD_NOT_FOUND: "Sorry, nothing here.",
  SUCCESS: "Success.",
  NOT_FOUND: "not found please check details again",
  ALREADY_EXIST: "already_exist.",
  NAME_REQUIRED: "name field is required.",
  EMAIL_REQUIRED: "email field is required.",
  DELETED_USER_ERROR: "Deleted User.",
  DELETED_USER: "This User is not exist longer.",
  TOKEN_REQUIRED_ERROR: "missing_token.",
  TOKEN_INVALID: "Token is invalid or Expire.",
  TOKEN_EXPIRED: "Session is expired.",
  TOKEN_EXPIRED_ERROR: "sessionExpired",
  TOKEN_VALIDATION: "Token is required.",
  ACCESS_DENIED_ERROR: "Access Denied: No Token Provided",
  DETAILS_NOT_FOUND: "Details not found",
  TYPE_REQUIRED: "type is required",
  VALID_TYPE: "Please use a valid type.",
  NAME_ALREADY_EXISTS: "Name already exists",
  INVALID_STATUS: "The selected status is invalid.",
  RECORD_CREATED: "Created successfully.",
  RECORD_DELETED: "Deleted successfully.",
  RECORD_UPDATED: "Updated successfully.",
  PHONE_INTEGER: "The mobileNumber must be an integer.",
  FILE_NAME_REQUIRED: "fileName field is required",
  OTP_REQUIRED: "OTP required.",
  WRONG_OTP: "Invalid Code",
  WRONG_OTP_MSG: "Sorry! code was mismatch",
  USER_ID_REQUIRED: "userId field is required.",
  USER_ID_NOT_FOUND: "userId not found",
  CATEGORY_REQUIRED: "Category field is required.",
  OTP_REQUIRED: "OTP required.",
  EXPIRE_DATE_REQUIRED: "expireDate field is required",
  EMAIL_ALREADY_EXISTS: "Email already exists!",
  USER_REGISTER_SUCCES: "User registered successfully",
  USER_LOGIN_SUCCESS: "Login successful",
  INVALID_EMAIL_OR_PASSWORD: "Invalid email or password",
  FAILED_TO_UPDATE_USER: "Failed to update user",
  FAILED_TO_DELETE_USER: "Failed to delete user",
  USER_UPDATE_SUCCESS: "User updated successfully",
  USER_DELETED_SUCCESS: "User deleted successfully",
  VALIDATION_SUCCESS: "Validation successful",
  USER_ID_NOT_EXIST: "User not found"
};

module.exports = constant;
